# Generated by Django 4.0 on 2022-09-30 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=15, verbose_name='Account number')),
                ('balance', models.DecimalField(decimal_places=1, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=1, max_digits=20)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=1, max_digits=20)),
                ('typ', models.IntegerField(choices=[(0, 'Deposit'), (1, 'Withdraw')])),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposit.deposit')),
            ],
        ),
    ]
