# Generated by Django 4.0 on 2022-09-30 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_no', models.CharField(max_length=15, verbose_name='Loan number')),
                ('amount', models.DecimalField(decimal_places=1, max_digits=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loan.loan')),
                ('withdraw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='deposit.withdrawal')),
            ],
        ),
    ]
